using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CodeGuardian.Core;

public sealed class RiskyCodeAnalyzer
{
    public async Task<IReadOnlyList<Finding>> AnalyzeAsync(
        Project project,
        CancellationToken cancellationToken = default)
    {
        var findings = new List<Finding>();

        foreach (var document in project.Documents.Where(d => d.SourceCodeKind == SourceCodeKind.Regular))
        {
            var root = await document.GetSyntaxRootAsync(cancellationToken);
            var semanticModel = await document.GetSemanticModelAsync(cancellationToken);
            if (root is null || semanticModel is null || IsGenerated(document, root))
            {
                continue;
            }

            foreach (var method in root.DescendantNodes().OfType<MethodDeclarationSyntax>())
            {
                var symbol = semanticModel.GetDeclaredSymbol(method, cancellationToken);
                if (method.Modifiers.Any(SyntaxKind.AsyncKeyword) && symbol?.ReturnsVoid == true)
                {
                    findings.Add(CreateFinding(
                        "CG101",
                        "Avoid 'async void'; return Task so callers can await failures.",
                        project,
                        method.Identifier.GetLocation()));
                }
            }

            foreach (var access in root.DescendantNodes().OfType<MemberAccessExpressionSyntax>())
            {
                var symbol = semanticModel.GetSymbolInfo(access, cancellationToken).Symbol;
                if (symbol is IPropertySymbol { Name: "Result" } property && IsTaskLike(property.ContainingType))
                {
                    findings.Add(CreateFinding(
                        "CG102",
                        "Blocking on Task.Result can deadlock or exhaust request threads; use await.",
                        project,
                        access.Name.GetLocation()));
                }
            }

            foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                var symbol = semanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol as IMethodSymbol;
                if (symbol is { Name: "Wait" } && IsTaskLike(symbol.ContainingType))
                {
                    findings.Add(CreateFinding(
                        "CG102",
                        "Blocking on Task.Wait() can deadlock or exhaust request threads; use await.",
                        project,
                        invocation.GetLocation()));
                }
            }

            foreach (var catchClause in root.DescendantNodes().OfType<CatchClauseSyntax>())
            {
                if (catchClause.Block.Statements.Count == 0)
                {
                    findings.Add(CreateFinding(
                        "CG103",
                        "Empty catch block silently hides failures.",
                        project,
                        catchClause.CatchKeyword.GetLocation()));
                }
            }
        }

        return findings;
    }

    private static bool IsGenerated(Document document, SyntaxNode root) =>
        document.Name.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
        document.Name.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) ||
        root.GetLeadingTrivia().ToFullString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);

    private static bool IsTaskLike(INamedTypeSymbol? type) =>
        type is not null &&
        type.ContainingNamespace.ToDisplayString() == "System.Threading.Tasks" &&
        type.Name is "Task" or "ValueTask";

    private static Finding CreateFinding(string ruleId, string message, Project project, Location location)
    {
        var span = location.GetLineSpan();
        return new Finding(
            ruleId,
            FindingSeverity.Warning,
            message,
            project.Name,
            span.Path,
            span.StartLinePosition.Line + 1,
            span.StartLinePosition.Character + 1);
    }
}
