<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>codeguardian</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CodeGuardian.Core/CodeGuardian.Core.csproj" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>
</Project>
